batch_size: 32
epochs: 100
es_patience: 10
lr: 0.001
model_params:
  in_channels: 1
  num_classes: 10
  # ECLayr params
  interval_1:
  - 0.053
  - 0.14
  interval_2:
  - 0.05
  - 0.95
  steps_1: 64
  steps_2: 64
  constr: "V"
  sublevel_1: True
  sublevel_2: False
  beta: 0.01
threshold: 0.001